server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: inventory
  password: inventory123
  url: jdbc:mysql://localhost:3306/inventory_db?useSSL=false&serverTimezone=UTC
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  validationQuery: "SELECT 1"
  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute

jwtSecret: "mySecretKey123ForInventorySystem"

logging:
  level: INFO
  loggers:
    com.example.inventory: DEBUG
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
      logFormat: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    - type: file
      threshold: ALL
      logFormat: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
      currentLogFilename: ./logs/inventory.log
      archivedLogFilenamePattern: ./logs/inventory-%d{yyyy-MM-dd}.log
      archivedFileCount: 5
      timeZone: UTC